language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      sudo: true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - cmake
            - make
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

script:
     - mkdir -p build
     - cd build
     - cmake -DCMAKE_BUILD_TYPE=Release .. 
     - make package

deploy:
  provider: releases
  api_key:
    secure: kTf8gUTZb4Nw3Pd30s+l/UIRz5v2xuxJKhuOtl9rVxR4SzNU/fHRjpM8XBMl2fv5CqUs/TXLqGoAhPaoWCajlpNS4wR8SUCgBaakXyNmEhrAGCw9HhUjuoVTauIqM3hxaouoQKuONctKgK2BBXQnHefV1BBsnhEPjgd1NlgJ4vzmqZDjqAO/k2vQoZ6BZE5TSLq5vLcsJ6EsZ6hcK4JzPqU/I6iXbuJ3/kuzCEiNKvlafUY99IyFsqkawW90hNhG21fCVqfY45t4IJ1457gzBqEaLjsNR1TPerXaSCNp3Y+Y77++Dupvu42m08/Z2eJJOsiHEwPyziL4kOgGhNLR0spE1R0hf1b+q1qoS9VQ018VcUiqwN6Ztr0LRyrA/f3H0cwgvUrbmYr3C0oYg3ZlMEhHiUd68940XOXkSWPnncs0ltJFJMsZeHOBZIVo/c+UzNLX0X+eTZuaVyfr0POl7nqHGqk0RFIUfMcjLKAQIo5wfeCH8vSalYYM1AAUFfpY6wGb9e9F7mFgYJUk1ETRy+8WGj/1SkLXEggViRqlpQ+ItKhB0l61gR4t4rG7sYpMgxW7QeKvOGzmxzfuJtw0vN3U6WH57ifLwmWg5MJFmqERcgH0c9mVDJAHFIgVRYpSlvcTqPiexNwOUbZ2i4lsx2rL+aJxdUeRawnkBIITIAA=
  file: build/g3log-1.3.2-Linux.deb
  on:
    repo: CosmicResearch/g3log
